name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: builder
      run: clang rde_build.c -Werror -Wall -Wextra -o builder
    - name: unit_tests
      run: ./builder -b=tests -m="[audio,rendering,obj,error,file_system]" && build/linux/debug/unit_tests/run_tests
    - name: build
      run: ./builder -b=engine -bt=release -m="[audio,rendering,obj,error,file_system]" 
