name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: builder
      run: clang rde_build.c -Werror -Wall -Wextra -o builder
    - name: build
      run: ./builder -b=engine -bt=release -m="[rendering,audio,error,obj,file_system]" 
